---
#
- name: Install needed software
  apt:
    name: '{{item}}'
    state: latest
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - python-minimal
    - aptitude

#
- name: Add docker apt keys
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 36A1D7869245C8950F966E92D8576A8BA88D21E9

#
- name: Update apt
  apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo ubuntu-trusty main'
    state: present

#
- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  apt:
    update_cache: yes
    cache_valid_time: 3600

#
- name: Install docker-engine
  apt:
    name: '{{item}}'
    state: latest
    force: yes
  with_items:
    - docker-engine

#
- name: Restart docker server
  service: name=docker state=restarted
